# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cfe28740a12f10462cf9d44e83b25c5978137ec966f44ebc257e0efa21e91380ae4ca82157e7675c37e6f0ace3bf9fb2f6c0255b6455d98e243d6861ad46ffd

test:
  secret_key_base: 4f0094727cde8a1a4c9ee79e9b898e176254952c2d89b4297436ef426228cc6a8d9cc7eb0a2e29edb2956dfb2210b8dd29ae25c3c52e535f6f0cef31ddd09d4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
